const offerLink = "vnd.youtube://www.youtube.com/redirect?event=comments&redir_token=QUFFLUhqa0cydEVNdl9vbklKS3g1eE1qQVJUUk5NajFBd3xBQ3Jtc0tsNEpsaHpQRjBTTkJnbzRPek5VdnYteXJZMUJnLTJtSlBJdEM5SVVsLXVFZmxMZUdtNHNEYWRNOHR4YXMzcGlJbG5teUxEbFA3ak1reDhxX25Xei1DbWtSczFQOVlhTy0xM19weF9MdHV3NnFBQmxvRQ&q=https%3A%2F%2Fv.ht%2Fa1gFZ&html_redirect=1 ";


